### ISSUE TITLE
It won't work

### ISSUE THREAD

**Issue by zkbutt** [kanxoramesh/webrtc-android-client#4]
It won't work. I think it won't download
com.remote.remote:remotedispatch:1.0.3

hint
Caused by: org.gradle.api.internal.artifacts.ivyservice.DefaultLenientConfiguration$ArtifactResolveException: Could not resolve all files for configuration ':app:debugCompileClasspath'.

**Comment by SayGoodLuck** [comment]
> It won't work. I think it won't download com.remote.remote:remotedispatch:1.0.3
> 
> hint Caused by: org.gradle.api.internal.artifacts.ivyservice.DefaultLenientConfiguration$ArtifactResolveException: Could not resolve all files for configuration ':app:debugCompileClasspath'.

I have a feeling that the author deliberately deleted some parts of the application to prevent the possibility of running the code locally. com.remote.remote.screenshare. is missing from the repository.

**Comment by kanxoramesh** [comment]
It is a library . Please reach out to me [pokhrelramesh1996@gmail.com] @SayGoodLuck  @zkbutt
